//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashBoard.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DC_UNIVERSITIES
    {
        public int ID { get; set; }
        public string Staff_Type { get; set; }
        public string Nationality { get; set; }
        public Nullable<double> CNT { get; set; }
        public string Gender { get; set; }
        public string UniversityName { get; set; }
    }
}
